# Generated by Django 6.0.3 on 2026-04-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('case_number', models.CharField(max_length=20)),
                ('doctor_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('product_id', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_description', models.TextField(blank=True, null=True)),
                ('production_lab', models.CharField(max_length=100)),
                ('mill_used', models.CharField(blank=True, max_length=100, null=True)),
                ('milling_technician', models.CharField(blank=True, max_length=100, null=True)),
                ('design_location', models.CharField(blank=True, max_length=100, null=True)),
                ('units', models.IntegerField(default=0)),
                ('original_case_number', models.CharField(blank=True, max_length=50, null=True)),
                ('original_month', models.CharField(blank=True, max_length=20, null=True)),
                ('original_production_lab', models.CharField(blank=True, max_length=100, null=True)),
                ('remake_reason', models.TextField(blank=True, null=True)),
                ('charge_doctor', models.BooleanField(default=False)),
                ('remake_units', models.IntegerField(default=0)),
                ('adjustment_units', models.IntegerField(default=0)),
                ('lab_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lab_discount_units', models.IntegerField(default=0)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
