# Generated by Django 6.0.3 on 2026-04-08 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remake',
            name='date_entered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
